version: '3.1'

services:
  db-1:
    image: postgres:13
    environment:
      - POSTGRES_DB=database_1
      - POSTGRES_USER=database_1
      - POSTGRES_PASSWORD=database_1
    volumes:
        - ./postgres_1:/var/lib/postgresql/data
    ports:
        - 5432:5432

  db-2:
    image: postgres:13
    environment:
      - POSTGRES_DB=database_2
      - POSTGRES_USER=database_2
      - POSTGRES_PASSWORD=database_2
    volumes:
        - ./postgres_2:/var/lib/postgresql/data
    ports:
        - 5433:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 8001
    volumes:
        - ./pgadmins:/var/lib/pgadmin
    ports:
        - 8001:8001
    depends_on:
        - db-1
        - db-2




